# Generated by Django 3.1.4 on 2020-12-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tag Name')),
                ('link', models.URLField(verbose_name='Link')),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('link', models.URLField(verbose_name='Link')),
                ('thumb', models.URLField(verbose_name='Thumb')),
                ('datetime', models.DateTimeField(verbose_name='Date Time')),
                ('keywords', models.ManyToManyField(to='core.Keyword')),
            ],
        ),
    ]
