# Generated by Django 3.1.4 on 2020-12-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_notice_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='campus',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
