# Generated by Django 3.1.4 on 2020-12-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_notice_campus'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='image',
            field=models.FilePathField(blank=True),
        ),
    ]
