# Generated by Django 3.1.4 on 2020-12-13 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201213_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='image',
            field=models.FilePathField(null=True),
        ),
    ]
