# Generated by Django 3.1.4 on 2020-12-13 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20201213_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='content',
        ),
    ]
