# Generated by Django 3.1.4 on 2020-12-14 11:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20201213_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailNewsletter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('sended_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.TextField()),
                ('sended_to', models.ManyToManyField(to='core.EmailNewsletter')),
            ],
        ),
    ]
