# Generated by Django 3.1.4 on 2020-12-15 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_delete_announcement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('category', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('link', models.URLField(verbose_name='Link')),
                ('thumb', models.URLField(blank=True, null=True, verbose_name='Thumb')),
                ('datetime', models.DateTimeField(verbose_name='Date Time')),
                ('campus', models.CharField(blank=True, max_length=50)),
                ('image', models.URLField(null=True)),
                ('keywords', models.ManyToManyField(to='core.Keyword')),
            ],
        ),
    ]
